export const ROUTE_HOME = 'ROUTE_HOME'
export const ROUTE_DISCOVER = 'ROUTE_DISCOVER'
export const ROUTE_CART = 'ROUTE_CART'
export const ROUTE_MINE = 'ROUTE_MINE'
export const ROUTE_INIT = 'ROUTE_INIT'
export const ROUTE_SEARCH = 'ROUTE_SEARCH'
export const ROUTE_MAIN = 'ROUTE_MAIN'